### ISSUE TITLE
Is there a way to hide one content when another is being viewed?

### ISSUE THREAD

**Issue by renegenoa** [lesterchan/wp-showhide#7]
I have two side by side content column and both of them has "show more" option which on being clicked shows the content. Is there a way, when one is clicked other closes down or does not display?

**Comment by lesterchan** [comment]
Sorry that is not what the plugin is designed for, so it is not possible.

**Comment by renegenoa** [comment]
Thnx for the prompt reply. Its a great plugin though!!!
